# Generated by Django 5.0.4 on 2024-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
