# Generated by Django 5.0.4 on 2024-10-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0002_alter_project_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='Project_name',
        ),
    ]
