# Generated by Django 5.0.4 on 2024-10-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0003_rename_name_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('deed_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('registration_date', models.DateField(blank=True)),
                ('mutation_status_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mutation_status_date', models.DateField(blank=True, null=True)),
                ('mutation_status_dcr', models.FileField(blank=True, null=True, upload_to='mutation_status_dcr/')),
                ('last_seller', models.CharField(blank=True, max_length=255)),
                ('buyer', models.CharField(blank=True, max_length=255)),
                ('name_of_buyer', models.CharField(blank=True, max_length=255)),
                ('type_of_deed', models.CharField(blank=True, max_length=100)),
                ('land_area_in_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('deed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('mouja', models.CharField(max_length=255)),
                ('khatian_cs', models.CharField(blank=True, max_length=100, null=True)),
                ('khatian_sa', models.CharField(blank=True, max_length=100, null=True)),
                ('khatian_rs', models.CharField(blank=True, max_length=100, null=True)),
                ('khatian_bs_brs', models.CharField(blank=True, max_length=100, null=True)),
                ('khatian_city_jorip', models.CharField(blank=True, max_length=100, null=True)),
                ('dag_cs', models.CharField(blank=True, max_length=100, null=True)),
                ('dag_sa', models.CharField(blank=True, max_length=100, null=True)),
                ('dag_rs', models.CharField(blank=True, max_length=100, null=True)),
                ('dag_bs_brs', models.CharField(blank=True, max_length=100, null=True)),
                ('dag_city_jorip', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_land', models.CharField(blank=True, max_length=100)),
                ('khajana_status', models.CharField(blank=True, max_length=50)),
                ('mortgage_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mortgage_deed', models.FileField(blank=True, null=True, upload_to='mortgage_deeds/')),
                ('mortgage_poa_deeds', models.FileField(blank=True, null=True, upload_to='poa_deeds/')),
                ('mortgage_date', models.DateField(blank=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_management.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
