# Generated by Django 5.0.4 on 2024-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0004_detail_delete_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='deed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='khajana_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='land_area_in_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name_of_buyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='type_of_deed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='type_of_land',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
