# Generated by Django 5.0.4 on 2024-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0005_alter_detail_buyer_alter_detail_deed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='mortgage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
