# Generated by Django 5.0.4 on 2024-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0006_alter_detail_mortgage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='deed_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
