# Generated by Django 5.0.4 on 2024-10-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0007_alter_detail_deed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='deed_number',
            field=models.PositiveIntegerField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='file_number',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
