# Generated by Django 5.0.4 on 2024-10-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0009_company_alter_detail_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deed_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deed_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='type_of_deed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_management.deed_type'),
        ),
    ]
