# Generated by Django 5.0.4 on 2024-10-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0010_deed_type_alter_detail_type_of_deed'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='khajana_document',
            field=models.FileField(blank=True, null=True, upload_to='khajana_document'),
        ),
    ]
