# Generated by Django 5.0.4 on 2024-10-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0012_bank_list_land_type_alter_detail_mortgage_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='khajana_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khajana_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='khajana_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_management.khajana_payment'),
        ),
    ]
