# Generated by Django 5.0.4 on 2024-10-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_management', '0013_fiscal_year_khajana_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='khajana_document',
        ),
        migrations.AddField(
            model_name='detail',
            name='khajana_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_management.fiscal_year'),
        ),
    ]
